### ISSUE TITLE
"Worksheet not specified" error when passing worksheet index 0

### ISSUE THREAD

**Issue by ryan-williams** [samcday/node-google-spreadsheets#33]
```sh
$ cat gsheet.js
#!/usr/bin/env node

var GoogleSpreadsheets = require("google-spreadsheets");

var key = process.argv[2];
var range = process.argv[3];

GoogleSpreadsheets.cells(
      {
        key: key,
        worksheet: 0,
        range: range
      },
      function(err, cells) {
        console.log("cells:", err, cells);
      }
);
$ gsheet.js 1Bb-SLy4E-alUUSJ68Qb5nNmZG6HsPbG2j6Ye_QZO77Y A1:A3
/Users/ryan/node_modules/google-spreadsheets/lib/spreadsheets.js:258
    throw new Error("Worksheet not specified.");
    ^

Error: Worksheet not specified.
    at Function.Spreadsheets.cells (/Users/ryan/node_modules/google-spreadsheets/lib/spreadsheets.js:258:11)
    at Object.<anonymous> (/Users/ryan/s/js-helpers/gsheet.js:8:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

Trying to load range `A1:A3` from [this sheet](https://docs.google.com/spreadsheets/d/1Bb-SLy4E-alUUSJ68Qb5nNmZG6HsPbG2j6Ye_QZO77Y/edit#gid=0).

**Comment by dmatt** [comment]
@ryan-williams I tried your `GoogleSpreadsheets.cells()` call and it seems that the `worksheet` key requires that the index start at `1`, not `0`. Found this in the README here:

>worksheet: (required) worksheet id. Can be a numeric index (starting from 1), or the proper string identifier for a worksheet.

https://github.com/samcday/node-google-spreadsheets#googlespreadsheetsrowsopts-callback

Unfortunately now, I'm getting an auth error even though my spreadsheet is public, and I'm not using auth.

>cells: Error: No access to that spreadsheet, check your auth.

**Comment by yipcma** [comment]
@dmatt make sure spreadsheet is published?
